name: Run Datadog Synthetic tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  datadog-synthetics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verificar se secrets estão disponíveis
        run: |
          if [ -z "${{ secrets.DD_API_KEY }}" ] || [ -z "${{ secrets.DD_APP_KEY }}" ]; then
            echo "Datadog API Key ou Application Key não configuradas."
            exit 1
          fi

      - name: Rodar testes sintéticos do Datadog
        uses: DataDog/synthetics-ci-github-action@v1.4.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          test_search_query: 'tag:e2e-tests' # Ajuste conforme as tags dos seus testes no Datadog

      # Opcional: Notificação de falha (exemplo para Slack)
      # - name: Notificar falha no Slack
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: '{"text":"Os testes sintéticos do Datadog falharam no repositório ad-genius-optimizer."}'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
